# Seata file.conf（file 模式兜底，生产建议切 Nacos config）
transport {
  type = "TCP"
  server = "NIO"
  heartbeat = true
  enableClientBatchSendRequest = true
}
service {
  vgroupMapping.mall-tx-group = "default"
  default.grouplist = "127.0.0.1:8091"
  enableDegrade = false
  disable = false
}
client {
  rm {
    reportSuccessEnable = false
  }
  tm {
    commitRetryCount = 5
    rollbackRetryCount = 5
  }
}
